### ISSUE TITLE
Scale doesn't change by using the radio buttons

### ISSUE THREAD

**Issue by thomassiu** [UBC-MDS/group10-worldcovid-dash-r#14]
When I click between the linear and log scale it does not change the data in the graphs, e.g. axis and the shape of the lines. 
Graphs are reloaded though.

**Comment by Kingslin0810** [comment]
this is fixed here - https://github.com/UBC-MDS/group10-worldcovid-dash-r/pull/16

**Comment by thomassiu** [comment]
fixed by #19
