### ISSUE TITLE
Heroku app

### ISSUE THREAD

**Issue by thomassiu** [UBC-MDS/group10-worldcovid-dash-r#2]
Hi all,

As I've reached the limit of opening the heroku app, can someone host the R version?
We can walkthrouth the steps again in the lab.

Thanks
Thomas

**Comment by Kingslin0810** [comment]
let me deploy and grant you all the access for - https://worldcovid-dashr.herokuapp.com/

**Comment by Kingslin0810** [comment]
wait; I believe each time we make the change and we would have to re-deploy. So I guess we don't need to deploy until milestone 4
